-- MySQL Script generated by MySQL Workbench
-- 03/15/16 08:52:24
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `iduser` INT NOT NULL COMMENT '',
  `nom` VARCHAR(45) NOT NULL COMMENT '',
  `prenom` VARCHAR(45) NOT NULL COMMENT '',
  `adressemail` VARCHAR(200) NOT NULL COMMENT '',
  `motdepasse` VARCHAR(200) NOT NULL COMMENT '',
  PRIMARY KEY (`iduser`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contact` (
  `idcontact` INT NOT NULL COMMENT '',
  `nom` VARCHAR(45) NOT NULL COMMENT '',
  `prenom` VARCHAR(45) NULL COMMENT '',
  `adressemail` VARCHAR(200) NULL COMMENT '',
  `user_iduser` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idcontact`)  COMMENT '',
  INDEX `fk_contact_user1_idx` (`user_iduser` ASC)  COMMENT '',
  CONSTRAINT `fk_contact_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sms` (
  `idsms` INT NOT NULL COMMENT '',
  `corps` VARCHAR(1000) NOT NULL COMMENT '',
  `dateEnvoie` TIMESTAMP NULL COMMENT '',
  `dateEnregistrement` VARCHAR(45) NULL COMMENT '',
  `user_iduser` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idsms`)  COMMENT '',
  INDEX `fk_sms_user1_idx` (`user_iduser` ASC)  COMMENT '',
  CONSTRAINT `fk_sms_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`compte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`compte` (
  `idcompte` INT NOT NULL COMMENT '',
  `country` VARCHAR(3) NOT NULL COMMENT '',
  `service` VARCHAR(45) NOT NULL COMMENT '',
  `contactId` VARCHAR(200) NOT NULL COMMENT '',
  `availableUnits` INT NOT NULL COMMENT '',
  `expires` TIMESTAMP NOT NULL COMMENT '',
  `scdescription` VARCHAR(1000) NOT NULL COMMENT '',
  `user_iduser` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idcompte`)  COMMENT '',
  INDEX `fk_compte_user1_idx` (`user_iduser` ASC)  COMMENT '',
  CONSTRAINT `fk_compte_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`groupe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`groupe` (
  `nomGroupe` VARCHAR(45) NULL COMMENT '',
  `idgroupe` INT NOT NULL COMMENT '',
  `user_iduser` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idgroupe`)  COMMENT '',
  INDEX `fk_groupe_user_idx` (`user_iduser` ASC)  COMMENT '',
  CONSTRAINT `fk_groupe_user`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`numero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`numero` (
  `numero` VARCHAR(100) NOT NULL COMMENT '',
  `contact_idcontact` INT NOT NULL COMMENT '',
  PRIMARY KEY (`numero`, `contact_idcontact`)  COMMENT '',
  INDEX `fk_numero_contact1_idx` (`contact_idcontact` ASC)  COMMENT '',
  CONSTRAINT `fk_numero_contact1`
    FOREIGN KEY (`contact_idcontact`)
    REFERENCES `mydb`.`contact` (`idcontact`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contact_has_groupe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contact_has_groupe` (
  `contact_idcontact` INT NOT NULL COMMENT '',
  `groupe_idgroupe` INT NOT NULL COMMENT '',
  PRIMARY KEY (`contact_idcontact`, `groupe_idgroupe`)  COMMENT '',
  INDEX `fk_contact_has_groupe_groupe1_idx` (`groupe_idgroupe` ASC)  COMMENT '',
  INDEX `fk_contact_has_groupe_contact1_idx` (`contact_idcontact` ASC)  COMMENT '',
  CONSTRAINT `fk_contact_has_groupe_contact1`
    FOREIGN KEY (`contact_idcontact`)
    REFERENCES `mydb`.`contact` (`idcontact`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contact_has_groupe_groupe1`
    FOREIGN KEY (`groupe_idgroupe`)
    REFERENCES `mydb`.`groupe` (`idgroupe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sms_has_contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sms_has_contact` (
  `sms_idsms` INT NOT NULL COMMENT '',
  `contact_idcontact` INT NOT NULL COMMENT '',
  `etat` VARCHAR(1) NOT NULL COMMENT '',
  PRIMARY KEY (`sms_idsms`, `contact_idcontact`)  COMMENT '',
  INDEX `fk_sms_has_contact_contact1_idx` (`contact_idcontact` ASC)  COMMENT '',
  INDEX `fk_sms_has_contact_sms1_idx` (`sms_idsms` ASC)  COMMENT '',
  CONSTRAINT `fk_sms_has_contact_sms1`
    FOREIGN KEY (`sms_idsms`)
    REFERENCES `mydb`.`sms` (`idsms`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sms_has_contact_contact1`
    FOREIGN KEY (`contact_idcontact`)
    REFERENCES `mydb`.`contact` (`idcontact`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
